apiVersion: v1
kind: Service
metadata:
  name: uaa
  labels:
    app: uaa
spec:
  selector:
    app: uaa
  ports:
  - name: uaa-port
    port: 8080
    targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: uaa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uaa
    spec:
      containers:
      - name: uaa
        image: splatform/stratos-uaa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: uaa